---
- name: Windows playbook
  hosts: all

  tasks:

  - name: Echo event
    win_shell: echo "This is my playbook"
    
  - name: Create directory structure
    win_file:
      path: C:\TempWorkshop2\
      state: directory
