---
- name: Windows playbook
  hosts: all
  gather_facts: yes

  vars:
    names:
      - Rajneesh
      - Chris
      - Gareth

  tasks:

  - name: Windows or Linux
    debug: msg="{{ ansible_system }}"

  - name: Windows or Linux
    debug: msg="IT IS RUNNING LINUX"
    when: ansible_system == "Linux"
    
  - name: Windows or Linux
    debug: msg="IT IS RUNNING WINDOWS"
    when: ansible_system == "Win32NT"

  - name: Echo event
    win_shell: echo "This is my playbook"
    
  - name: Run command
    win_command: whoami
    register: command_output
      
  - name: Debug Message
    debug: msg="The output from whoami is '{{ command_output.stdout }}'"
