---
- name: Windows playbook
  hosts: all

  vars:
    names:
      - Rajneesh
      - Chris
      - Gareth

  tasks:

  - name: Echo event
    win_shell: echo "This is my playbook"
    
  - name: Run command
    win_command: whoami
    register: command_output
      
  - name: Debug Message
    debug: msg="The output from whoami is: '{{ command_output.stdout }}'"
