---
- name: Windows playbook
  hosts: all

  vars:
    names:
      - Rajneesh
      - Chris
      - Gareth

  tasks:

  - name: Echo event
    win_shell: echo "This is my playbook"
    
  - name: Create directory structure
    win_file:
      path: C:\TempWorkshop2\
      state: directory
      
  - debug:
      var: "{{ names }}"
