---
- name: Windows playbook
  hosts: all
  gather_facts: no

  vars:
    names:
      - Rajneesh
      - Chris
      - Gareth

  tasks:

  - name: System version
    debug: msg="{{ ansible_system }}"
    ignore_errors: True

  - name: Linux
    debug: msg="{{ item }}"
    loop: "{{ names }}"
    
