---
- name: Windows playbook
  hosts: all
  gather_facts: no

  vars:
    names:
      - Rajneesh
      - Chris
      - Gareth

  tasks:

  - name: Linux
    debug: msg="{{ item }}"
    loop:
    - c:\file1.txt
    - c:\file2.txt
    
