---
- name: Windows playbook
  hosts: all
  gather_facts: no
  vars:
    my_text: |
      This is my text that I wrote
      
      this is the third line

  tasks:

  - name: Run on Ansible server
    debug: msg="{{ my_text }}"
    delegate_to: localhost
  
  - name: Include some tasks from another file
    include_tasks: imported_tasks.yml

    
